/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.sql.Date;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.VIP;
import modele.ModeleJComboBoxPays;

/**
 *
 * @author Alain
 */
public class FenetreSaisieVIP extends javax.swing.JDialog {

    private VIP vip;
    private boolean etatSortie;
    private ModeleJComboBoxPays leModeleJComboBox;

    public FenetreSaisieVIP(java.awt.Frame parent, VIP vip, ModeleJComboBoxPays leModeleJComboBox) {
        super(parent, true);  // mode modal
        this.leModeleJComboBox=leModeleJComboBox;
        try{
            leModeleJComboBox.chargerLesPays();
        }
        catch(Exception ex){
            Logger.getLogger(FenetreSaisieVIP.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.vip = vip;
        etatSortie = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txPrenom = new javax.swing.JTextField();
        txNom = new javax.swing.JTextField();
        lbNom = new javax.swing.JLabel();
        lbJob = new javax.swing.JLabel();
        btValid = new javax.swing.JButton();
        txCivilite = new javax.swing.JTextField();
        txDateNaissance = new javax.swing.JTextField();
        txLieuNaissance = new javax.swing.JTextField();
        txCodeRole = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxPays = new javax.swing.JComboBox();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saisie d'un employé");

        txPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPrenomActionPerformed(evt);
            }
        });

        lbNom.setText("Nom");

        lbJob.setText("Prénom");

        btValid.setText("Valider");
        btValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValidActionPerformed(evt);
            }
        });

        txCivilite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCiviliteActionPerformed(evt);
            }
        });

        jLabel1.setText("Civilité");

        jLabel2.setText("Date de naissance");

        jLabel3.setText("Lieu de naissance");

        jLabel4.setText("codeRole");

        jLabel5.setText("Pays");

        comboBoxPays.setModel(leModeleJComboBox);
        comboBoxPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPaysActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNom, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(txNom, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbJob, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(txCivilite)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txDateNaissance)
                                            .addComponent(txLieuNaissance)
                                            .addComponent(txCodeRole))
                                        .addGap(41, 41, 41))
                                    .addComponent(comboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btValid)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNom)
                    .addComponent(txNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJob)
                    .addComponent(txPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCivilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txLieuNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCodeRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btValid)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValidActionPerformed
        // TODO add your handling code here:
        try {
            if (txNom.getText().isEmpty()) {
                throw new Exception("champ nom vide");
            }
            vip.setNomVIP(txNom.getText());
            if (txPrenom.getText().isEmpty()) {
                throw new Exception("champ prénom vide");
            }
            vip.setPrenomVIP(txPrenom.getText());
            if (txCivilite.getText().isEmpty()) {
                throw new Exception("champ civilité vide");
            }
            vip.setCivilite(txCivilite.getText());
            if (txDateNaissance.getText().isEmpty()) {
                throw new Exception("champ date de naissance vide");
            }
            vip.setDateNaissance(Date.valueOf(txDateNaissance.getText()));
            if (txLieuNaissance.getText().isEmpty()) {
                throw new Exception("champ lieu de naissance vide");
            }
            vip.setLieuNaissance(txLieuNaissance.getText());
            if (txCodeRole.getText().isEmpty()) {
                throw new Exception("champ codeRole vide");
            }
            vip.setCodeRole(txCodeRole.getText());
            if(comboBoxPays.getSelectedItem().toString().isEmpty()){
                throw new Exception("champ Pays vide");
            }
            vip.setPays(comboBoxPays.getSelectedItem().toString());
            vip.setCodeStatut("C");
            //vip.setPays("C");
            etatSortie = true;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btValidActionPerformed

    private void txPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPrenomActionPerformed

    private void txCiviliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCiviliteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCiviliteActionPerformed

    private void comboBoxPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxPaysActionPerformed

    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btValid;
    private javax.swing.JComboBox comboBoxPays;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbJob;
    private javax.swing.JLabel lbNom;
    private javax.swing.JTextField txCivilite;
    private javax.swing.JTextField txCodeRole;
    private javax.swing.JTextField txDateNaissance;
    private javax.swing.JTextField txLieuNaissance;
    private javax.swing.JTextField txNom;
    private javax.swing.JTextField txPrenom;
    // End of variables declaration//GEN-END:variables
}
